WITH desired_categories(slug, name, description, cover_image) AS (
  VALUES
    ('islamic-studies', 'Islamic Studies', 'Islamic Studies books and learning resources.', '/images/categories/placeholder.svg'),
    ('aqeedah', 'Aqeedah', 'Aqeedah books and learning resources.', '/images/categories/placeholder.svg'),
    ('tawheed', 'Tawheed', 'Tawheed books and learning resources.', '/images/categories/placeholder.svg'),
    ('stories-of-the-prophets', 'Stories of the Prophets', 'Stories of the Prophets books and learning resources.', '/images/categories/placeholder.svg'),
    ('stories-from-the-quran', 'Stories from the Qur''an', 'Stories from the Qur''an books and learning resources.', '/images/categories/placeholder.svg'),
    ('sahabah', 'Sahabah', 'Sahabah books and learning resources.', '/images/categories/placeholder.svg'),
    ('mothers-of-the-believers', 'Mothers of the Believers', 'Mothers of the Believers books and learning resources.', '/images/categories/placeholder.svg'),
    ('good-manners', 'Good Manners', 'Good Manners books and learning resources.', '/images/categories/placeholder.svg'),
    ('duas-and-adhkar', 'Duas & Adhkar', 'Duas & Adhkar books and learning resources.', '/images/categories/placeholder.svg'),
    ('salah', 'Salah', 'Salah books and learning resources.', '/images/categories/placeholder.svg'),
    ('ramadan', 'Ramadan', 'Ramadan books and learning resources.', '/images/categories/placeholder.svg'),
    ('eid', 'Eid', 'Eid books and learning resources.', '/images/categories/placeholder.svg'),
    ('hajj-and-umrah', 'Hajj & Umrah', 'Hajj & Umrah books and learning resources.', '/images/categories/placeholder.svg'),
    ('daily-sunnah', 'Daily Sunnah', 'Daily Sunnah books and learning resources.', '/images/categories/placeholder.svg'),
    ('quran-and-arabic', 'Qur''an & Arabic', 'Qur''an & Arabic books and learning resources.', '/images/categories/placeholder.svg'),
    ('arabic-alphabet', 'Arabic Alphabet', 'Arabic Alphabet books and learning resources.', '/images/categories/placeholder.svg'),
    ('arabic-reading', 'Arabic Reading', 'Arabic Reading books and learning resources.', '/images/categories/placeholder.svg'),
    ('arabic-writing', 'Arabic Writing', 'Arabic Writing books and learning resources.', '/images/categories/placeholder.svg'),
    ('tajweed', 'Tajweed', 'Tajweed books and learning resources.', '/images/categories/placeholder.svg'),
    ('quran-reading', 'Qur''an Reading', 'Qur''an Reading books and learning resources.', '/images/categories/placeholder.svg'),
    ('memorization', 'Memorization', 'Memorization books and learning resources.', '/images/categories/placeholder.svg'),
    ('educational', 'Educational', 'Educational books and learning resources.', '/images/categories/placeholder.svg'),
    ('early-learning', 'Early Learning', 'Early Learning books and learning resources.', '/images/categories/placeholder.svg'),
    ('english', 'English', 'English books and learning resources.', '/images/categories/placeholder.svg'),
    ('mathematics', 'Mathematics', 'Mathematics books and learning resources.', '/images/categories/placeholder.svg'),
    ('science', 'Science', 'Science books and learning resources.', '/images/categories/placeholder.svg'),
    ('social-studies', 'Social Studies', 'Social Studies books and learning resources.', '/images/categories/placeholder.svg'),
    ('stem', 'STEM', 'STEM books and learning resources.', '/images/categories/placeholder.svg'),
    ('languages', 'Languages', 'Languages books and learning resources.', '/images/categories/placeholder.svg'),
    ('activities-and-printables', 'Activities & Printables', 'Activities & Printables books and learning resources.', '/images/categories/placeholder.svg'),
    ('worksheets', 'Worksheets', 'Worksheets books and learning resources.', '/images/categories/placeholder.svg'),
    ('coloring-books', 'Coloring Books', 'Coloring Books books and learning resources.', '/images/categories/placeholder.svg'),
    ('flashcards', 'Flashcards', 'Flashcards books and learning resources.', '/images/categories/placeholder.svg'),
    ('crafts', 'Crafts', 'Crafts books and learning resources.', '/images/categories/placeholder.svg'),
    ('posters', 'Posters', 'Posters books and learning resources.', '/images/categories/placeholder.svg'),
    ('activity-books', 'Activity Books', 'Activity Books books and learning resources.', '/images/categories/placeholder.svg'),
    ('games', 'Games', 'Games books and learning resources.', '/images/categories/placeholder.svg'),
    ('puzzles', 'Puzzles', 'Puzzles books and learning resources.', '/images/categories/placeholder.svg'),
    ('shop-by-age', 'Shop by Age', 'Shop by Age books and learning resources.', '/images/categories/placeholder.svg'),
    ('0-3-years', '0-3 Years', '0-3 Years books and learning resources.', '/images/categories/placeholder.svg'),
    ('3-6-years', '3-6 Years', '3-6 Years books and learning resources.', '/images/categories/placeholder.svg'),
    ('6-9-years', '6-9 Years', '6-9 Years books and learning resources.', '/images/categories/placeholder.svg'),
    ('9-12-years', '9-12 Years', '9-12 Years books and learning resources.', '/images/categories/placeholder.svg'),
    ('12-plus-years', '12+ Years', '12+ Years books and learning resources.', '/images/categories/placeholder.svg')
)
INSERT INTO "categories" ("id", "slug", "name", "description", "coverImage", "createdAt")
SELECT
  'cat_' || replace(replace(slug, '-', '_'), '+', 'plus'),
  slug,
  name,
  description,
  cover_image,
  CURRENT_TIMESTAMP
FROM desired_categories
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "coverImage" = EXCLUDED."coverImage";

DELETE FROM "categories"
WHERE "slug" NOT IN (
  'islamic-studies',
  'aqeedah',
  'tawheed',
  'stories-of-the-prophets',
  'stories-from-the-quran',
  'sahabah',
  'mothers-of-the-believers',
  'good-manners',
  'duas-and-adhkar',
  'salah',
  'ramadan',
  'eid',
  'hajj-and-umrah',
  'daily-sunnah',
  'quran-and-arabic',
  'arabic-alphabet',
  'arabic-reading',
  'arabic-writing',
  'tajweed',
  'quran-reading',
  'memorization',
  'educational',
  'early-learning',
  'english',
  'mathematics',
  'science',
  'social-studies',
  'stem',
  'languages',
  'activities-and-printables',
  'worksheets',
  'coloring-books',
  'flashcards',
  'crafts',
  'posters',
  'activity-books',
  'games',
  'puzzles',
  'shop-by-age',
  '0-3-years',
  '3-6-years',
  '6-9-years',
  '9-12-years',
  '12-plus-years'
);
