import {
  BookOpen,
  Landmark,
  Star,
  Palette,
  Languages,
  Heart,
  PenTool,
  Calculator,
  Baby,
  Gamepad2,
  type LucideIcon,
} from "lucide-react";

/** Small lucide-icon stand-in for each real category slug — used wherever a
 * category needs a compact visual identity (filter checkboxes, chips) but a
 * full cover-image thumbnail would be too heavy. Falls back to BookOpen. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "0-3-years": Baby,
  "3-6-years": Baby,
  "6-9-years": Baby,
  "9-12-years": Baby,
  "12-plus-years": Baby,
  "activities-and-printables": PenTool,
  "activity-books": BookOpen,
  "arabic-alphabet": Languages,
  "arabic-reading": Languages,
  "arabic-writing": Languages,
  "aqeedah": Landmark,
  "coloring-books": Palette,
  crafts: Palette,
  "daily-sunnah": Heart,
  "duas-and-adhkar": Heart,
  "early-learning": Baby,
  educational: BookOpen,
  eid: Star,
  flashcards: BookOpen,
  games: Gamepad2,
  "good-manners": Heart,
  "hajj-and-umrah": Landmark,
  "islamic-studies": Landmark,
  "languages": Languages,
  "mathematics": Calculator,
  memorization: BookOpen,
  "mothers-of-the-believers": Heart,
  posters: PenTool,
  puzzles: Gamepad2,
  "quran-and-arabic": BookOpen,
  "quran-reading": BookOpen,
  ramadan: Star,
  sahabah: Landmark,
  salah: Landmark,
  science: BookOpen,
  "shop-by-age": Baby,
  "social-studies": BookOpen,
  stem: BookOpen,
  "stories-from-the-quran": BookOpen,
  "stories-of-the-prophets": Landmark,
  tajweed: BookOpen,
  tawheed: Landmark,
  worksheets: PenTool,
};

export function getCategoryIcon(slug: string): LucideIcon {
  return CATEGORY_ICONS[slug] ?? BookOpen;
}
